Description: Downloads the latest version and makes a pkg. Then, uploads the package to the Jamf Pro Server and creates a Self Service Policy and Smart Group.
Identifier: com.github.smithjw-actions.jamf.upload.Docker
ParentRecipe: com.github.smithjw.pkg.Docker-Universal
MinimumVersion: '2.9'

Input:
  NAME: Docker
  SOFTWARE_TITLE: '%NAME%'
  arm_dl_url: 'https://desktop.docker.com/mac/main/arm64/Docker.dmg'
  CATEGORY: Utilities
  intel_dl_url: 'https://desktop.docker.com/mac/main/amd64/Docker.dmg'
  PACKAGE_INFO: autopkg
  PKG_NAME_MATCH: '%SOFTWARE_TITLE%-'
  PKG_TO_KEEP: '2'
  REMOVE_OLD_PACKAGES: 'true'

Process:
  - Processor: com.github.grahampugh.jamf-upload.processors/JamfPackageUploader
    Arguments:
      pkg_category: '%CATEGORY%'
      pkg_info: '%PACKAGE_INFO%'

  - Processor: com.github.grahampugh.recipes.postprocessors/LastRecipeRunResult

  - Processor: StopProcessingIf
    Arguments:
      predicate: '%REMOVE_OLD_PACKAGES% == false'

  - Processor: com.github.grahampugh.jamf-upload.processors/JamfPackageCleaner
    Arguments:
      pkg_name_match: '%PKG_NAME_MATCH%'
      versions_to_keep: '%PKG_TO_KEEP%'
